git add common/fault_injection/fault_injector_random.h
git add common/fault_injection/fault_injection.h
git add common/fault_injection/fault_injection.cc
git add common/fault_injection/fault_injector_random.cc
git add common/system/magic_server.cc
git add common/system/magic_client.cc
git add common/system/magic_server.h
git add common/core/memory_subsystem/pr_l1_pr_l2_dram_directory_msi/dram_cntlr.h
git add common/core/memory_subsystem/pr_l1_pr_l2_dram_directory_msi/Raul.h
git add common/core/memory_subsystem/pr_l1_pr_l2_dram_directory_msi/dram_cntlr.cc
git add common/core/memory_subsystem/cache/cache_base.h
git add common/core/memory_subsystem/cache/cache_set_random.h
git add common/core/memory_subsystem/cache/cache_set_lru2.h
git add common/core/memory_subsystem/cache/Raul.h
git add common/core/memory_subsystem/cache/cache_set_lru2.cc
git add common/core/memory_subsystem/cache/cache_set.h
git add common/core/memory_subsystem/cache/cache.cc
git add common/core/memory_subsystem/cache/cache.h
git add common/core/memory_subsystem/cache/cache_set.cc
git add common/core/memory_subsystem/parametric_dram_directory_msi/cache_cntlr.h
git add common/core/memory_subsystem/parametric_dram_directory_msi/memory_manager.cc
git add common/core/memory_subsystem/parametric_dram_directory_msi/cache_cntlr.cc
git add common/core/memory_subsystem/memory_manager_base.h
git add common/core/core.cc
git add config/raul.cfg
git add config/raul_2.cfg
git add data_significance/amean/amean.cpp
git add data_significance/amean/make.py
git add data_significance/amean/script.sh
git add data_significance/laplacian/laplacian.cpp
git add data_significance/laplacian/make.py
git add data_significance/laplacian/script.sh
git add data_significance/sharp/sharp.cpp
git add data_significance/sharp/make.py
git add data_significance/sharp/script.sh
git add data_significance/sobel/sobel.cpp
git add data_significance/sobel/convolution.hpp
git add data_significance/sobel/convolution.cpp
git add data_significance/sobel/mydefines.h
git add data_significance/sobel/make.py
git add data_significance/sobel/script.sh
git add data_significance/datasig.py
git add data_significance/flty.h
git add include/sim_api.h
git add mcpat/added/core.cc
git add mcpat/added/logic.h
git add mcpat/added/logic.cc
git add mcpat/added/XML_Parse.cc
git add mcpat/added/XML_Parse.h
git add mcpat/added/sharedcache.cc
git add mcpat/added/processor.cc
git add mcpat/added/cacti/mat.cc
git add mcpat/added/cacti/io.cc
git add mcpat/added/cacti/cacti_interface.h
git add mcpat/added/cacti/technology.cc
git add probability_analysis/run.cpp
git add probability_analysis/Makefile
git add probability_analysis/APPROX_ADD.matrix
git add probability_analysis/APPROX_MUL.matrix
git add probability_analysis/DRAM_1T_45nm.matrix
git add probability_analysis/DRAM_Flikker.matrix
git add probability_analysis/L1_RP_SRAM_6T_45nm.matrix
git add probability_analysis/L1_RP_SRAM_6T_65nm.matrix
git add probability_analysis/L1_WP_SRAM_6T_45nm.matrix
git add probability_analysis/L1_WP_SRAM_6T_65nm.matrix
git add probability_analysis/L2_RP_SRAM_6T_45nm.matrix
git add probability_analysis/L2_RP_SRAM_6T_65nm.matrix
git add probability_analysis/L2_WP_SRAM_6T_45nm.matrix
git add probability_analysis/L2_WP_SRAM_6T_65nm.matrix
git add test/amean/amean.cpp
git add test/amean/faultProbabilities.txt
git add test/amean/faulty_psnr.sh
git add test/amean/make.py
git add test/amean/Makefile
git add test/amean/script.sh
git add test/api/api.c
git add test/api/Makefile
git add test/laplacian/laplacian.cpp
git add test/laplacian/faultProbabilities.txt
git add test/laplacian/make.py
git add test/laplacian/Makefile
git add test/laplacian/script.sh
git add test/shared/Makefile.shared
git add test/sharp/sharp.cpp
git add test/sharp/faultProbabilities.txt
git add test/sharp/make.py
git add test/sharp/Makefile
git add test/sharp/script.sh
git add test/sobel/mydefines.h
git add test/sobel/sobel.cpp
git add test/sobel/make.py
git add test/sobel/Makefile
git add test/sobel/script.sh
git add test/sobel/faultProbabilities.txt
git add tools/raul_mcpat.py
git add git_add.sh